version: "3"
services:
  prerender:
    image: tvanro/prerender-alpine
    ports:
      - 3002:3000
    environment:
      - MEMORY_CACHE=0
      - CACHE_MAXSIZE=1000
      - CACHE_TTL=6000
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./:/home/node
